// Chainlink CRE Action Handlers for Canton/Daml Orchestration
// Generated by CantonFlow Canvas

interface CantonConfig {
  ledgerApi: string;
  authToken: string;
}

interface StepContext {
  config: Record<string, unknown>;
  previousSteps: Record<string, { contract_id: string; result: unknown }>;
  secrets: CantonConfig;
}

export async function canton_create(ctx: StepContext) {
  const { ledgerApi, authToken } = ctx.secrets;
  const templateId = ctx.config.template_id as string;
  const initialState = ctx.config.initial_state as string;
  const parties = ctx.config.parties as string[];

  const payload: Record<string, unknown> = {
    processId: crypto.randomUUID(),
    currentState: initialState,
  };

  // Map parties from config
  for (const party of parties) {
    payload[party.toLowerCase()] = party;
  }

  const res = await fetch(`${ledgerApi}/v1/create`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${authToken}` },
    body: JSON.stringify({ templateId, payload, meta: { actAs: [parties[0]] } }),
  });

  if (!res.ok) throw new Error(`Canton create failed: ${res.status}`);
  const data = await res.json();
  return { contract_id: data.contractId, result: data };
}

export async function canton_exercise(ctx: StepContext) {
  const { ledgerApi, authToken } = ctx.secrets;
  const choice = ctx.config.choice as string;
  const controller = ctx.config.controller as string;
  const templateId = ctx.config.template_id as string;
  const contractId = resolveRef(ctx.config.contract_id as string, ctx.previousSteps);

  const res = await fetch(`${ledgerApi}/v1/exercise`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${authToken}` },
    body: JSON.stringify({
      templateId,
      contractId,
      choice,
      argument: {},
      meta: { actAs: [controller] },
    }),
  });

  if (!res.ok) throw new Error(`Canton exercise ${choice} failed: ${res.status}`);
  const data = await res.json();
  return { contract_id: data.exerciseResult, result: data };
}

export async function gateway_evaluate(ctx: StepContext) {
  const branches = ctx.config.branches as Array<{ name: string; condition?: string }>;
  // TODO: Evaluate conditions against contract state
  // For now, selects the first branch
  return { selected_branch: branches?.[0]?.name || 'default', contract_id: '' };
}

function resolveRef(ref: string, steps: Record<string, { contract_id: string }>): string {
  const match = ref.match(/\{\{steps\.(\w+)\.contract_id\}\}/);
  if (match && steps[match[1]]) return steps[match[1]].contract_id;
  return ref;
}