// Proc_Client — Cloudflare Workflow Orchestrator
// Generated by CantonFlow Canvas
// Drives Daml contract state machine via Canton JSON API

import { WorkflowEntrypoint, WorkflowStep, WorkflowEvent } from 'cloudflare:workers';

export interface Env {
  CANTON_LEDGER_API: string;  // e.g. "https://canton-node.example.com"
  CANTON_AUTH_TOKEN: string;
}

interface WorkflowParams {
  processId: string;
  bridgeRelay: string;  // Party identifier
  client: string;  // Party identifier
  evaluator: string;  // Party identifier
  provider: string;  // Party identifier
}

interface CantonExerciseResult {
  exerciseResult: string;  // New contract ID
  events: unknown[];
}

async function exerciseChoice(
  env: Env,
  contractId: string,
  choice: string,
  args: Record<string, unknown>,
  actAs: string
): Promise<CantonExerciseResult> {
  const res = await fetch(`${env.CANTON_LEDGER_API}/v1/exercise`, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      'Authorization': `Bearer ${env.CANTON_AUTH_TOKEN}`,
    },
    body: JSON.stringify({
      templateId: 'Main:Proc_ClientProcess',
      contractId,
      choice,
      argument: args,
      meta: { actAs: [actAs] },
    }),
  });
  if (!res.ok) throw new Error(`Canton API ${res.status}: ${await res.text()}`);
  return res.json() as Promise<CantonExerciseResult>;
}

async function createContract(
  env: Env,
  payload: Record<string, unknown>,
  actAs: string
): Promise<{ contractId: string }> {
  const res = await fetch(`${env.CANTON_LEDGER_API}/v1/create`, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      'Authorization': `Bearer ${env.CANTON_AUTH_TOKEN}`,
    },
    body: JSON.stringify({
      templateId: 'Main:Proc_ClientProcess',
      payload,
      meta: { actAs: [actAs] },
    }),
  });
  if (!res.ok) throw new Error(`Canton create ${res.status}: ${await res.text()}`);
  return res.json() as Promise<{ contractId: string }>;
}

export class ProcClientWorkflow extends WorkflowEntrypoint<Env, WorkflowParams> {
  async run(event: WorkflowEvent<WorkflowParams>, step: WorkflowStep) {
    const params = event.payload;

    // Create the initial Daml contract
    const initial = await step.do('create-contract', async () => {
      return createContract(this.env, {
        processId: params.processId,
        currentState: 'Start_Client',
        bridgeRelay: params.bridgeRelay,
        client: params.client,
        evaluator: params.evaluator,
        provider: params.provider,
      }, params.bridgeRelay);
    });

    let contractId = initial.contractId;

    // userTask: Create Payment Obligation
    // NOTE: This step requires human input — use step.sleep() or an external signal
    await step.sleep('wait-for-create-payment-obligation', '1 hour');
    const createPaymentObligationResult = await step.do('create-payment-obligation', async () => {
      return exerciseChoice(this.env, contractId, 'CreatePaymentObligation', {}, params.client);
    });
    contractId = createPaymentObligationResult.exerciseResult;

    // serviceTask: Lock WrappedUSDC
    const lockWrappedUSDCResult = await step.do('lock-wrappedusdc', async () => {
      return exerciseChoice(this.env, contractId, 'LockWrappedUSDC', {}, params.client);
    });
    contractId = lockWrappedUSDCResult.exerciseResult;

    // userTask: Receive Settlement Confirmation
    // NOTE: This step requires human input — use step.sleep() or an external signal
    await step.sleep('wait-for-receive-settlement-confirmation', '1 hour');
    const receiveSettlementConfirmationResult = await step.do('receive-settlement-confirmation', async () => {
      return exerciseChoice(this.env, contractId, 'ReceiveSettlementConfirmation', {}, params.client);
    });
    contractId = receiveSettlementConfirmationResult.exerciseResult;

    // Complete the workflow
    await step.do('complete', async () => {
      return exerciseChoice(this.env, contractId, 'JobComplete', {}, params.bridgeRelay);
    });
  }
}